spring:
  application:
    name: jpa-test-api

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/test;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE

# 서버 포트
server:
  port: 8080

# 로깅 레벨
logging:
  level:
    org:
      hibernate: INFO

